// Maincategory Constants
export const CREATE_MAINCATEGORY = "CREATE_MAINCATEGORY"
export const CREATE_MAINCATEGORY_RED = "CREATE_MAINCATEGORY_RED"
export const GET_MAINCATEGORY = "GET_MAINCATEGORY"
export const GET_MAINCATEGORY_RED = "GET_MAINCATEGORY_RED"
export const UPDATE_MAINCATEGORY = "UPDATE_MAINCATEGORY"
export const UPDATE_MAINCATEGORY_RED = "UPDATE_MAINCATEGORY_RED"
export const DELETE_MAINCATEGORY = "DELETE_MAINCATEGORY"
export const DELETE_MAINCATEGORY_RED = "DELETE_MAINCATEGORY_RED"


// Subcategory Constants
export const CREATE_SUBCATEGORY = "CREATE_SUBCATEGORY"
export const CREATE_SUBCATEGORY_RED = "CREATE_SUBCATEGORY_RED"
export const GET_SUBCATEGORY = "GET_SUBCATEGORY"
export const GET_SUBCATEGORY_RED = "GET_SUBCATEGORY_RED"
export const UPDATE_SUBCATEGORY = "UPDATE_SUBCATEGORY"
export const UPDATE_SUBCATEGORY_RED = "UPDATE_SUBCATEGORY_RED"
export const DELETE_SUBCATEGORY = "DELETE_SUBCATEGORY"
export const DELETE_SUBCATEGORY_RED = "DELETE_SUBCATEGORY_RED"


// Brand Constants
export const CREATE_BRAND = "CREATE_BRAND"
export const CREATE_BRAND_RED = "CREATE_BRAND_RED"
export const GET_BRAND = "GET_BRAND"
export const GET_BRAND_RED = "GET_BRAND_RED"
export const UPDATE_BRAND = "UPDATE_BRAND"
export const UPDATE_BRAND_RED = "UPDATE_BRAND_RED"
export const DELETE_BRAND = "DELETE_BRAND"
export const DELETE_BRAND_RED = "DELETE_BRAND_RED"


// Testimonial Constants
export const CREATE_TESTIMONIAL = "CREATE_TESTIMONIAL"
export const CREATE_TESTIMONIAL_RED = "CREATE_TESTIMONIAL_RED"
export const GET_TESTIMONIAL = "GET_TESTIMONIAL"
export const GET_TESTIMONIAL_RED = "GET_TESTIMONIAL_RED"
export const UPDATE_TESTIMONIAL = "UPDATE_TESTIMONIAL"
export const UPDATE_TESTIMONIAL_RED = "UPDATE_TESTIMONIAL_RED"
export const DELETE_TESTIMONIAL = "DELETE_TESTIMONIAL"
export const DELETE_TESTIMONIAL_RED = "DELETE_TESTIMONIAL_RED"


// Product Constants
export const CREATE_PRODUCT = "CREATE_PRODUCT"
export const CREATE_PRODUCT_RED = "CREATE_PRODUCT_RED"
export const GET_PRODUCT = "GET_PRODUCT"
export const GET_PRODUCT_RED = "GET_PRODUCT_RED"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const UPDATE_PRODUCT_RED = "UPDATE_PRODUCT_RED"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const DELETE_PRODUCT_RED = "DELETE_PRODUCT_RED"

// Service Constants
export const CREATE_SERVICE = "CREATE_SERVICE"
export const CREATE_SERVICE_RED = "CREATE_SERVICE_RED"
export const GET_SERVICE = "GET_SERVICE"
export const GET_SERVICE_RED = "GET_SERVICE_RED"
export const UPDATE_SERVICE = "UPDATE_SERVICE"
export const UPDATE_SERVICE_RED = "UPDATE_SERVICE_RED"
export const DELETE_SERVICE = "DELETE_SERVICE"
export const DELETE_SERVICE_RED = "DELETE_SERVICE_RED"

// Feature Constants
export const CREATE_FEATURE = "CREATE_FEATURE"
export const CREATE_FEATURE_RED = "CREATE_FEATURE_RED"
export const GET_FEATURE = "GET_FEATURE"
export const GET_FEATURE_RED = "GET_FEATURE_RED"
export const UPDATE_FEATURE = "UPDATE_FEATURE"
export const UPDATE_FEATURE_RED = "UPDATE_FEATURE_RED"
export const DELETE_FEATURE = "DELETE_FEATURE"
export const DELETE_FEATURE_RED = "DELETE_FEATURE_RED"


// Fact Constants
export const CREATE_FACT = "CREATE_FACT"
export const CREATE_FACT_RED = "CREATE_FACT_RED"
export const GET_FACT = "GET_FACT"
export const GET_FACT_RED = "GET_FACT_RED"
export const UPDATE_FACT = "UPDATE_FACT"
export const UPDATE_FACT_RED = "UPDATE_FACT_RED"
export const DELETE_FACT = "DELETE_FACT"
export const DELETE_FACT_RED = "DELETE_FACT_RED"


// Cart Constants
export const CREATE_CART = "CREATE_CART"
export const CREATE_CART_RED = "CREATE_CART_RED"
export const GET_CART = "GET_CART"
export const GET_CART_RED = "GET_CART_RED"
export const UPDATE_CART = "UPDATE_CART"
export const UPDATE_CART_RED = "UPDATE_CART_RED"
export const DELETE_CART = "DELETE_CART"
export const DELETE_CART_RED = "DELETE_CART_RED"

// Wishlist Constants
export const CREATE_WISHLIST = "CREATE_WISHLIST"
export const CREATE_WISHLIST_RED = "CREATE_WISHLIST_RED"
export const GET_WISHLIST = "GET_WISHLIST"
export const GET_WISHLIST_RED = "GET_WISHLIST_RED"
export const UPDATE_WISHLIST = "UPDATE_WISHLIST"
export const UPDATE_WISHLIST_RED = "UPDATE_WISHLIST_RED"
export const DELETE_WISHLIST = "DELETE_WISHLIST"
export const DELETE_WISHLIST_RED = "DELETE_WISHLIST_RED"

// Checkout Constants
export const CREATE_CHECKOUT = "CREATE_CHECKOUT"
export const CREATE_CHECKOUT_RED = "CREATE_CHECKOUT_RED"
export const GET_CHECKOUT = "GET_CHECKOUT"
export const GET_CHECKOUT_RED = "GET_CHECKOUT_RED"
export const UPDATE_CHECKOUT = "UPDATE_CHECKOUT"
export const UPDATE_CHECKOUT_RED = "UPDATE_CHECKOUT_RED"
export const DELETE_CHECKOUT = "DELETE_CHECKOUT"
export const DELETE_CHECKOUT_RED = "DELETE_CHECKOUT_RED"

// Newsletter Constants
export const CREATE_NEWSLETTER = "CREATE_NEWSLETTER"
export const CREATE_NEWSLETTER_RED = "CREATE_NEWSLETTER_RED"
export const GET_NEWSLETTER = "GET_NEWSLETTER"
export const GET_NEWSLETTER_RED = "GET_NEWSLETTER_RED"
export const UPDATE_NEWSLETTER = "UPDATE_NEWSLETTER"
export const UPDATE_NEWSLETTER_RED = "UPDATE_NEWSLETTER_RED"
export const DELETE_NEWSLETTER = "DELETE_NEWSLETTER"
export const DELETE_NEWSLETTER_RED = "DELETE_NEWSLETTER_RED"

// Contact Us Constants
export const CREATE_CONTACTUS = "CREATE_CONTACTUS"
export const CREATE_CONTACTUS_RED = "CREATE_CONTACTUS_RED"
export const GET_CONTACTUS = "GET_CONTACTUS"
export const GET_CONTACTUS_RED = "GET_CONTACTUS_RED"
export const UPDATE_CONTACTUS = "UPDATE_CONTACTUS"
export const UPDATE_CONTACTUS_RED = "UPDATE_CONTACTUS_RED"
export const DELETE_CONTACTUS = "DELETE_CONTACTUS"
export const DELETE_CONTACTUS_RED = "DELETE_CONTACTUS_RED"

// User Constants
export const CREATE_USER = "CREATE_USER"
export const CREATE_USER_RED = "CREATE_USER_RED"
export const GET_USER = "GET_USER"
export const GET_USER_RED = "GET_USER_RED"
export const UPDATE_USER = "UPDATE_USER"
export const UPDATE_USER_RED = "UPDATE_USER_RED"
export const DELETE_USER = "DELETE_USER"
export const DELETE_USER_RED = "DELETE_USER_RED"